### ISSUE TITLE
Obtaining Indices of Corrected Polygons

### ISSUE THREAD

**Issue by philipc2** [gadomski/antimeridian#45]
Hello! I'm a developer of the [UXarray](https://github.com/UXARRAY/uxarray) Python Package.

I am currently working visualizing Unstructured Grids with Datashader. Our data is represented in lat/lon coordinates and in order to visualize it in 2D, we need to split the antimeridian polygons (which this package has been perfect for). Below a few visualizations that I've been able to develop with the corrected polygons. 

### Before Splitting 
![image](https://github.com/gadomski/antimeridian/assets/67855069/2a4a95ac-9fe0-4e29-b50d-51a89f323f38)

### After Splitting 
![image](https://github.com/gadomski/antimeridian/assets/67855069/03e97daf-c551-443b-9880-b687d3a05b63)

### Before Splitting
![image](https://github.com/gadomski/antimeridian/assets/67855069/563cef8d-56c2-4e49-980c-9601edf44f19)

### After Splitting
![image](https://github.com/gadomski/antimeridian/assets/67855069/5f69fa20-7bb0-4425-81ba-ca4e0b4c1acd)

We are also interested in visualizing data at each face. However, I have not been able to identify which polygons were split. Below is a snippet of the code that I am using to process our polygons.

```Python
# obtain polygon shells for shapely polygon construction
polygon_shells = self.polygon_shells

# construct a list of shapely polygons
polygons = [Polygon(shell) for shell in polygon_shells]

# represent as a MultiPolygon for splitting
multi_polygon = MultiPolygon(polygons)

# correct antimeridian polygons
multi_polygon_corrected = fix_multi_polygon(multi_polygon)

# convert back to a list of shapely polygons
polygons_corrected = list(multi_polygon_corrected.geoms)

# prepare polygons for GeoDataFrame
geometry = MultiPolygonArray(polygons_corrected)

# store the geometry in our GeoDataFrame
gdf = GeoDataFrame({"geometry": geometry})
```

Since the new number of Polygons in our `GeoDataFrame` is larger than we began with originally, there's no clear way on how to map our data variables (which lie on the original set of polygons) to the corrected set. We would like to have a mapping from the original set of polygons into the newly constructed polygons. For example:

Let's say we have a MultiPolygon that contains Polygons [A, B, C, D], where Polygon B need to be corrected

After running `fix_multi_polygon` we now have an output [A, B1, B2, C, D], where B1 and B2 are the corrected Polygons. 

Having a variable that could map the indices of the split polygon into the indices of the output polygon (in this case index 1 in our original multipolygon maps to indices 1, 2)

Do you have any suggestions on how to tackle this using this package?

**Comment by gadomski** [comment]
Off the top, you could just loop through the component polygons and see if they split, e.g. (psuedo-python):

```python
fixed_polygons = list()
unchanged_polygons = list()
for polygon in multi_polygon:
    fixed = antimeridian.fix_polygon(polygon)
    if fixed.is_multipolygon():
        fixed_polygons.extend(fixed)
    else:
        unchanged_polygons.append(polygon)
```

Obviously you'll need to change the method calls, etc to be valid shapely, but that's the general idea. Is that what you're looking for?

**Comment by philipc2** [comment]
> Off the top, you could just loop through the component polygons and see if they split, e.g. (psuedo-python):
> 
> ```python
> fixed_polygons = list()
> unchanged_polygons = list()
> for polygon in multi_polygon:
>     fixed = antimeridian.fix_polygon(polygon)
>     if fixed.is_multipolygon():
>         fixed_polygons.extend(fixed)
>     else:
>         unchanged_polygons.append(polygon)
> ```
> 
> Obviously you'll need to change the method calls, etc to be valid shapely, but that's the general idea. Is that what you're looking for?

Thanks for the quick response! I'll give this a try, however I was getting some unexpected behavior earlier using `fix_polygon` on each Polygon. I'll post an update later this evening! 

However, the proposed method you commented would be adequate!

**Comment by gadomski** [comment]
> Thanks for the quick response! I'll give this a try, however I was getting some unexpected behavior earlier using fix_polygon on each Polygon. I'll post an update later this evening!

Yeah, if something's weird let me know.

Cool use-case, btw, thanks for sharing!

**Comment by philipc2** [comment]
Here's the following changes that I made:
```Python
# obtain polygon shells for shapely polygon construction
polygon_shells = self.polygon_shells

# construct a list of shapely polygons
polygons = [Polygon(shell) for shell in polygon_shells]

# attempt to fix each polygon
corrected_polygons = [fix_polygon(P) for P in polygons]

# prepare polygons for GeoDataFrame
geometry = MultiPolygonArray(corrected_polygons)

# store the geometry in our GeoDataFrame
gdf = GeoDataFrame({"geometry": geometry})
```

With this approach, we don't need to keep track of the indices since `fix_polygon` will produce a MultiPolygon in place of the invalid Polygon, so the original data can still map to it. 


## Successful Example

### Split using `fix_multi_polygon` (ignore the higher resolution plot)
![image](https://github.com/gadomski/antimeridian/assets/67855069/a099782b-b60a-46ee-9eaf-18465a65cce6)


### Split using `fix_polygon`
![image](https://github.com/gadomski/antimeridian/assets/67855069/ae2d203c-0203-4442-a798-a8743709d55c)


## Interesting Example
### Split using `fix_multi_polygon`
![image](https://github.com/gadomski/antimeridian/assets/67855069/d6af99ea-f62f-41b1-a0bf-3ce2919cbab1)


### Split using `fix_polygon`
![image](https://github.com/gadomski/antimeridian/assets/67855069/82f96115-480b-4a47-b328-212e4ef5b023)

To be fair, this may be an issue with the dataset, but I'm confused on why both methods produce different results. All of my other sample datasets appear to have the same results regardless on which method I used for fixing the antimeridian issues. 

Even after splitting the MultiPolygons into individual polygons, the same visualization artifact is still present.

**Comment by gadomski** [comment]
Interesting. Can you provide the multi-polygon from the second example so I can try to reproduce locally?

I do see two strange areas in the "correct" image so something unusual does seem to be afoot.

![249345925-d6af99ea-f62f-41b1-a0bf-3ce2919cbab1](https://github.com/gadomski/antimeridian/assets/58314/a73212c2-8adf-4955-81d7-5af10dac5726)

**Comment by philipc2** [comment]
[output_shapefiles.zip](https://github.com/gadomski/antimeridian/files/11895531/output_shapefiles.zip)

I've attached the outputs as shape files.

**Comment by gadomski** [comment]
@philipc2 I just checked all three shapefiles you provided, and they appeared more-or-less identical. All three were feature collections, and the only difference I could see is that some of the files had multi-polygons where others had those multi-polygons broken out into two separate polygons.

To get a reproducible example, can you do me a favor and provide a GeoJSON file of a single mutli-polygon (not a feature collection) that produces incorrect results when split polygon-by-polygon using `fix_polygon`, and produces correct results when split using `fix_multi_polygon`?

As a side note, the shapefiles you provided couldn't be opened out-of-the-box by GDAL -- I needed to set `SHAPE_RESTORE_SHX=1` to open them (e.g. `SHAPE_RESTORE_SHX=1 ogr2ogr c.json output_shapefiles/fix_polygon_multi_output.shp`).

**Comment by philipc2** [comment]
@gadomski 

Apologies for the inconvenient file format! I can get you a reproducible example as you described later today.

**Comment by philipc2** [comment]
Some Updates:

There is a single polygon that is split incorrectly in the second example that I showcased. Below is a visualization of the grid excluding that single polygon, which is correct except for the hole that we saw earlier. 

<img width="787" alt="image" src="https://github.com/gadomski/antimeridian/assets/67855069/6afb3e1a-87ce-4268-8295-053eccd0f0b1">


The polygon in question was constructed with these coordinates: 

```
array([[-176.78115373,  -18.58572933],
       [-173.71026732,  -14.73835555],
       [-176.88248512,  -12.82925277],
       [ 180.        ,  -15.7250416 ],
       [-176.78115373,  -18.58572933]])
```

The result after splitting the polygon is the following: 
```
MultiPolygon([[[-180.0, 90.0, -180.0, -90.0, 180.0, -90.0, 180.0, 90.0, -180.0, 90.0], [-176.78115372679827, -18.585729334295202, -173.71026732304864, -14.738355553590093, -176.88248512435254, -12.829252765997333, 179.99999999999997, -15.725041604285156, -176.78115372679827, -18.585729334295202]]])
```

This is the result when `fix_winding` is set to `False`. However, if we set it to `True` we get the following plot (of all the faces), which is consistent with `fix_multi_poly` result. 

<img width="879" alt="image" src="https://github.com/gadomski/antimeridian/assets/67855069/b1062ba1-e49e-41e7-9227-ce824ff33180">

**Comment by gadomski** [comment]
So the polygon your provided is a bit of a strange one, because it has a corner _exactly_ on the antimeridian. This leads to a split where one of the resulting polygons is just a line of points on the antimeridian (note that this command line example uses an as-of-yet unreleased feature that allows reading from standard input):

```shell
$ echo '{"type":"Polygon","coordinates":[[[-176.78115373,-18.58572933],[-173.71026732,-14.73835555],[-176.88248512,-12.82925277],[180,-15.7250416],[-176.78115373,-18.58572933]]]}' | antimeridian fix - | jq
{
  "type": "MultiPolygon",
  "coordinates": [
    [
      [
        [
          -180,
          -17.1618087
        ],
        [
          -176.78115373,
          -18.58572933
        ],
        [
          -173.71026732,
          -14.73835555
        ],
        [
          -176.88248512,
          -12.82925277
        ],
        [
          -180,
          -14.2708507
        ],
        [
          -180,
          -17.1618087
        ]
      ]
    ],
    [
      [
        [
          180,
          -14.2708507
        ],
        [
          180,
          -15.7250416
        ],
        [
          180,
          -17.1618087
        ],
        [
          180,
          -14.2708507
        ]
      ]
    ]
  ]
}
```

It might be reasonable for this library to drop any output polygons that have _all_ of their points on the same antimeridian, since that's probably not what the user wants. What do you think @philipc2?

**Comment by gadomski** [comment]
@philipc2 I fixed the "point on the antimeridian" case in https://github.com/gadomski/antimeridian/pull/49. If you can install from **main** (e.g. `pip install git+https://github.com/gadomski/anitmeridian`) and see if you get better results, that would be helpful. Thanks!

**Comment by philipc2** [comment]
Hi @gadomski 

With the most recent changes, it still appears that I'm getting the same results. 

![image](https://github.com/gadomski/antimeridian/assets/67855069/5252c50a-d70a-4630-8999-2017fe8e9de7)

```Python
MultiPolygon([[[-176.78115372679827, -18.585729334295202, 
179.99999999999997, -15.725041604285156, 
-176.88248512435254, -12.829252765997333, 
-173.71026732304864, -14.738355553590093, 
-176.78115372679827, -18.585729334295202]]])
```

Additionally, I'm getting the `fix_winding` warning message when `fix_winding` is `False`.

<img width="1315" alt="image" src="https://github.com/gadomski/antimeridian/assets/67855069/fdc4826d-3b81-4e22-8bcf-912c2bf11775">

**Comment by philipc2** [comment]
**Update:**

It appears that something funky is going on with my Jupyter Environment, testing it within pytest appears to be working as expected. 

I'll post an updated visualization once I resolve my environment issues, but thank you so much for putting together this hotfix so quickly! 😃

**Comment by philipc2** [comment]
@gadomski 

After some further digging, turns out my environment actually wasn't the issue. It seems to be a floating point issue with how  `180.0` was represented in my `polygon_shells`

At first glance, both sets of coordinates look the same:
<img width="579" alt="image" src="https://github.com/gadomski/antimeridian/assets/67855069/eea309f3-b58c-4801-b779-8bb31fc4b9a1">

When we take a deeper look into both arrays, we can see that the one we internally is much more precise, however it is still close to to the one we tested on:

<img width="414" alt="image" src="https://github.com/gadomski/antimeridian/assets/67855069/75a07f0a-d68f-4879-8032-5de1eca6a24e">


The culprit is our "180.0" is actually not exactly "180.0"

<img width="441" alt="image" src="https://github.com/gadomski/antimeridian/assets/67855069/952d2de2-464d-4229-a77d-810164da2c0d">

Rounding this value to "180.0" and then performing the splitting works as expected. 

Instead of checking whether a point is 180 (`point == 180.0`), we should check for `np.isclose(point, 180.0`) to handle these  instances.

I'll raise an issue for this.

**Comment by gadomski** [comment]
Thanks for the digging! Hopefully this was fixed in #52, can you check?

**Comment by philipc2** [comment]
It's working now! 

<img width="1303" alt="image" src="https://github.com/gadomski/antimeridian/assets/67855069/9c47d049-c09e-411a-802b-62927d1c4fa9">

Closing this issue since everything is working as expected now. Thanks for all the help! I'll do some testing on some other datasets and make sure to raise an issue if anything comes up!
